### ISSUE TITLE
Add flags to cuda-build.sh - use system nvcc, nvcc's gencode flag

### ISSUE THREAD

**Issue by reikdas** [scikit-hep/awkward#445]
We should add a flag to allow `cuda-build.sh` to use the system nvcc to compile the CUDA source files, instead of always using docker to do so. 
Also, it would be good to allow the user to set their own options to nvcc's `--gencode` flag - https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-steering-gpu-code-generation-generate-code

**Comment by jpivarski** [comment]
> We should add a flag to allow `cuda-build.sh` to use the system nvcc to compile the CUDA source files, instead of always using docker to do so.

Is the download or storage of the Docker image a problem? Using the system nvcc could be a non-default option.

I had considerable trouble installing an nvcc that is consistent with my compiler (gcc) because I use conda to install a compiler. There are two ways to install nvcc with conda; the one that worked involved downloading a 6 GB install script. (The conda package was 4 kB, but the "installing" phase took over an hour because of that internal install script.) The Docker image is itself 6 GB, but at least I know where it is and why it's there.

Also, it must be in a Docker image for the Azure build test, since that's by far the easiest way to guarantee that the Azure node is configured properly. Fortunately, Azure is well-connected and a 6 GB download in every CI run isn't a big deal!

> Also, it would be good to allow the user to set their own options to nvcc's `--gencode` flag - https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-steering-gpu-code-generation-generate-code

@trickarcher suggested that we compile in CUDA 9.0 because it works equally well on later systems. As I understand it, the PTX (virtual architecture) produced by a given version of CUDA gets translated into device-specific bytecode (real architecture) anyway, so what benefit would it be to generate PTX for different CUDA versions?

**Comment by jpivarski** [comment]
By the way, if you want this (item 1, the flag for native nvcc), go ahead and do it.

The cuda-build.sh script is pretty simple, so adding a second option in an order-independent way would mean having to check both orders—beyond that, we should think about real solutions. But while we're still talking about just two flags, we can do the hacky thing and check all combinations of order (both of them).

**Comment by reikdas** [comment]
> Is the download or storage of the Docker image a problem? Using the system nvcc could be a non-default option.

It just seems weird that we need docker to compile the CUDA code. I understand that we need it for AWS, but I feel that we should still provide a way to use the system nvcc to compile the code.

> By the way, if you want this (item 1, the flag for native nvcc), go ahead and do it.

Thanks!

> @trickarcher suggested that we compile in CUDA 9.0 because it works equally well on later systems. As I understand it, the PTX (virtual architecture) produced by a given version of CUDA gets translated into device-specific bytecode (real architecture) anyway, so what benefit would it be to generate PTX for different CUDA versions?

The bytecode generated by nvcc if no flags are specified is the lowest supported architecture and compute values for the installed version of CUDA. Architecture is backwards compatible - code compiled for `compute_35` would also work on `compute_60`, so we don't _need_ users to pass the appropriate arch and compute flags for their hardware to nvcc, but if you have more recent hardware and the bytecode generated is for the lowest supported architecture, then you might be losing out on some optimizations for newer hardware or utilizing newer instructions.
And when you say "generate PTX for different CUDA versions" do you mean generating bytecode for architecture not supported by the installed CUDA version? I don't mean that. If one tried to compile to a lower compute/sm than supported by the installed version of CUDA, they will get a compilation error I think.

**Comment by jpivarski** [comment]
> The bytecode generated by nvcc if no flags are specified is the lowest supported architecture and compute values for the installed version of CUDA. Architecture is backwards compatible - code compiled for `compute_35` would also work on `compute_60`, so we don't _need_ users to pass the appropriate arch and compute flags for their hardware to nvcc, but if you have more recent hardware and the bytecode generated is for the lowest supported architecture, then you might be losing out on some optimizations for newer hardware or utilizing newer instructions.

Okay, but we have to compile for the least common denominator because the wheel we deploy could be used anywhere. (Users with hardware that's too old for CUDA 9.0 are out of luck.) We don't have any plans for users to be able to compile their own copy of awkward1-cuda-kernels: if that's what you have in mind, that would be a new path, and a _very_ tricky one to get right.

**Comment by reikdas** [comment]
> We don't have any plans for users to be able to compile their own copy of awkward1-cuda-kernels: if that's what you have in mind, that would be a new path, and a very tricky one to get right.

I just realised that users will be getting the compiled CUDA kernels from PyPI and only developers will need to compile the CUDA source code using `cuda-build.sh`. This definitely removes any requirement for the second feature request (user defined `gencode` values) and reduces how strongly I felt about adding a choice for using the system nvcc - if I decide to add it, it will definetely be after everything else is done. 
Sorry about that :( 
Should we close this issue and perhaps create a new one later if I decide to add a flag to `cuda-build.sh` to use system nvcc to compile the CUDA source?

**Comment by jpivarski** [comment]
If you're not planning to do it right away, let's close the issue. If at any point you think it would help you to add it, add it in a pull request and I'll check it there. That helps to keep the issues board clear, which I need to prioritize work.

(Actually, I'll close it now so we don't forget.)
