### PR TITLE
Try again on visibility and also ensure -frtti

### PR DESCRIPTION
**Pull request by jpivarski**

### CODE REVIEW

**Comment by veprbl** [comment]
ffae43aa45d99e32d9242f21544f10cd8529b282 fails: https://gist.github.com/989007ff77cd929ed3aaf1e985374c8b

On my side I've reverted to llvmlite 0.30.0 and numba 0.46.0 and doing a bisect of awkward between 0.1.38 and master. I'm getting some intermediate revisions at which tests fail to collect because of:
```
ModuleNotFoundError: No module named 'pybind11_tests'
```
I do "git submodules update --recursive", but that doesn't help. Are you familiar with this issue?

**Comment by jpivarski** [comment]
I've been working continuously on this. I think that the RTTI issue are actually related to the visibility warnings I've been trying to get rid of on MacOS because those visibility warnings are all related to `typeinfo`.

Since pybind11 requires "hidden" visibility, all of the projects that I build have "hidden" visibility: libawkward-cpu-kernels, libawkward, and the Python extension modules. Symbols that actually do need to be visible are explicitly labeled with `__attribute__((visibility("default")))` (through a macro). It looks like Clang also has `__attribute__((type_visibility("default")))`, and I'm trying to figure out how to use that.

Since debugging through CI is extremely painstaking, I've installed Clang (for Linux) and I'm trying to use that. (Sorry it's taking a while.)

As for

```
ModuleNotFoundError: No module named 'pybind11_tests'
```

No, I'm not familiar with that error. We should not be running pybind11_tests—I don't know why it's trying to on your system.

**Comment by veprbl** [comment]
a390222a03435ec073bbb1541123d4de215e9709 fails: https://gist.github.com/b4b14ccaeeacafb57c884c282d29574d

**Comment by veprbl** [comment]
a49f5b90f0fdd25c1fa8689cc41f3c685c3d2179 fails: https://gist.github.com/veprbl/1aa32f4a436aebf35e1e3d30362c1559
1b99eba1ff3e2e48c2c9f8ab4608240c4178f5da fails: https://gist.github.com/99576ea7fc34e2c7cdd1758a408e4efe

**Comment by jpivarski** [comment]
I've given up trying to run Clang on my computer and I'm just debugging through continuous integration. All of the tests pass, but the MacOS tests have a lot of warnings about not being able to link `typeinfo` symbols. As I said above, I highly suspect that's relevant.

**Comment by veprbl** [comment]
a502209cc4ca17bf8067f5a81aaed71bec682447 fails: https://gist.github.com/ce9ffea8cb4d8a34aa539605a41a729c

**Comment by veprbl** [comment]
@jpivarski I think the clang idea is not a bad one. I rebuilt python38 (not python37 like I did macOS) and awkward's dependencies with clang on linux and managed to produce a single failure: https://gist.github.com/dd9f4889bede80de6f65231e407affa3 I don't think it's the relevant one, though.

**Comment by veprbl** [comment]
23600ea3e666c2eb8fb5b49f9ec43e91b0680ad9 fails: https://gist.github.com/20dc37fb15b4739403bfa29987739bb5

**Comment by jpivarski** [comment]
You're right, that error isn't relevant. However, I wasn't able to get clang to link on Linux—there are so many `undefined reference` errors that I can't scroll through them. I just don't know what needs to be done to get clang to work in place of gcc.

**Comment by jpivarski** [comment]
I had been selecting clang by setting the environment variable `CXX` to its full path. Now I'm trying to set `CMAKE_CXX_COMPILER` to clang's full path. I'm thinking that maybe setting only `CXX` might have swapped the compiler without also swapping the linker.

Well, there's a zillion linker errors again.

**Comment by jpivarski** [comment]
Am I right in thinking that I shouldn't use `ld` when compiling with clang? Because on my testing laptop, it compiles with clang (no problems) and links with `ld` with many errors.

**Comment by veprbl** [comment]
Could you show me your errors?

**Comment by jpivarski** [comment]
The end of the errors is

```
/home/pivarski/miniconda3/bin/ld: operations.cpp:(.text.startup+0x14): undefined reference to `std::ios_base::Init::~Init()'
/home/pivarski/miniconda3/bin/ld: libawkward-cpu-kernels-static.a(reducers.cpp.o): in function `_GLOBAL__sub_I_reducers.cpp':
reducers.cpp:(.text.startup+0xd): undefined reference to `std::ios_base::Init::Init()'
/home/pivarski/miniconda3/bin/ld: reducers.cpp:(.text.startup+0x14): undefined reference to `std::ios_base::Init::~Init()'
/home/pivarski/miniconda3/bin/ld: libawkward-cpu-kernels-static.a(util.cpp.o): in function `_GLOBAL__sub_I_util.cpp':
util.cpp:(.text.startup+0xd): undefined reference to `std::ios_base::Init::Init()'
/home/pivarski/miniconda3/bin/ld: util.cpp:(.text.startup+0x14): undefined reference to `std::ios_base::Init::~Init()'
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/test0030.dir/build.make:85: recipe for target 'test0030' failed
make[2]: *** [test0030] Error 1
CMakeFiles/Makefile2:120: recipe for target 'CMakeFiles/test0030.dir/all' failed
make[1]: *** [CMakeFiles/test0030.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

but the beginning is beyond my (giant) scroll buffer.

**Comment by jpivarski** [comment]
I think it's complaining about every symbol in the project.

**Comment by veprbl** [comment]
The result of my bisect:
e9f6ba0ca393ee37ed1b5dabd85ab0e2df8e341c is the first bad commit
I had to do "rm -rf pybind11/tests" to fix the collection error.
This time I did not bother updating submodules:
```
# git submodule status
 e43e1cc01ae6d4e4e5ba10557a057d7f3d5ece0d pybind11 (v2.3.0)
 f54b0e47a08782a6131cc3d60f94d038fa6e0a51 rapidjson (v1.1.0)
```

**Comment by jpivarski** [comment]
> I had to do "rm -rf pybind11/tests" to fix the collection error.

I realize now why you were seeing the pybind11_tests error: I've always run pytest with an explicit target:

```bash
pytest -vv tests
```

**Comment by jpivarski** [comment]
> The result of my bisect:
> [e9f6ba0](https://github.com/scikit-hep/awkward-1.0/commit/e9f6ba0ca393ee37ed1b5dabd85ab0e2df8e341c) is the first bad commit

That's a very interesting result, because it did change the build procedure. A monolithic Python extension module was broken into three extension modules. But that's unrelated to the warnings that I have been trying to get rid of all this time: the warnings come before any Python modules are compiled.

So now I have to think about how I could possibly test this. That refactoring was a big change, made long ago.

**Comment by veprbl** [comment]
> So now I have to think about how I could possibly test this. That refactoring was a big change, made long ago.

And somehow e9f6ba0ca393ee37ed1b5dabd85ab0e2df8e341c doesn't have any of those warnings we were chasing after:
https://gist.github.com/4cddda4da02e6e7e14ca04e27c11f46d

**Comment by jpivarski** [comment]
@veprbl This last commit probably doesn't fix the linker MacOS warnings, but it might fix the error that you see.

It could be that `typeinfo` was lost when an object created in one of the 3 extension modules was accessed in another, since these were distinct .dylib files and we're having trouble with `typeinfo` symbols anyway. With only 1 extension module, it's definitely the same one and it should see its own symbols.

Let me know how it fares. Thanks!

**Comment by veprbl** [comment]
ce9c2fb2bea2489eb05048c2630070d52c70b09c passes: https://gist.github.com/80118ce327992a5615f6ff9e3b2822e0

**Comment by jpivarski** [comment]
@veprbl Sorry about the noise on #210: this was a good chance to get CI working for PRs from forks.

Once it ran, I was getting errors from both MacOS and Windows ([here](https://dev.azure.com/jpivarski/Scikit-HEP/_build/results?buildId=1816&view=results)). Your changes managed to get MacOS on Azure to see the RTTI error—it might have been an accident that prevented it from materializing, something like a race in which symbols from the "layout" extension module overrode symbols from the "types" extension module in one case and vice-versa in the other. If we were that close to a bug, then it's too brittle to allow.

For Windows, I learned rather early on that you can't link a shared library to a shared library: the dependency must be a static library. I don't remember the details, but that was the conclusion I came to about 6 months ago. Now (in #210) they're failing with segfaults. I'd rather not revisit that.

There is one combination that works for everybody: the current state of #209. I have un-refactored the 3 extension modules into 1 extension module, and I think I can live with that. The refactoring didn't live up to its goals: [linker time wasn't improved](https://github.com/scikit-hep/awkward-1.0/pull/116) and the difficulty compiling a dependent C++ project was not related to how many Python extension modules the project was split into. (In fact, it might have suffered from the same kind of brittleness as you encountered, but I haven't been testing it on MacOS.)

Also, I really wanted to split into a lot of extension modules, but it could only be 3 because of various C++ constraints. Now I the `ak.layout`, `ak.types`, and `ak._io` modules are actually Python modules that pass objects from `ak._ext`. I could break them down into smaller, more logical pieces, now that the C++ constraints are not limiting the problem. The only ugly thing is that the names of these classes include `_ext` in their names, but maybe that's a good reminder to know which are pure Python and which are not.

So I'm favoring this solution (#209 over #210), since it seems to solve all the constraints, but I should check that "dependent project" again, first.

**Comment by jpivarski** [comment]
@veprbl The dependent project had some minor bugs as a result of not being in continuous integration (for other reasons: I can't find the installed paths on the Azure box), but otherwise it seemed to work flawlessly. I'm happy with restoring the monolithic Python extension.

Meanwhile, what were the things you did with `RPATH`?

```cmake
  if(APPLE)
    set_target_properties(layout PROPERTIES BUILD_WITH_INSTALL_RPATH TRUE INSTALL_RPATH "@loader_path")
  else()
    set_target_properties(layout PROPERTIES BUILD_RPATH_USE_ORIGIN TRUE)
  endif()
```

As I understand it, `RPATH` is the Darwin equivalent of Linux's `LD_LIBRARY_PATH`. Would the above be a good idea to apply independently of whether I build a monolithic Python extension module or not? Because if it is, I'll try adding it to this PR before merging and deploying a new version.

**Comment by veprbl** [comment]
> As I understand it, `RPATH` is the Darwin equivalent of Linux's `LD_LIBRARY_PATH`.

No, this is not correct. The `DYLD_LIBRARY_PATH` is Darwin's equivalent of the `LD_LIBRARY_PATH`.

> Would the above be a good idea to apply independently of whether I build a monolithic Python extension module or not? Because if it is, I'll try adding it to this PR before merging and deploying a new version.

RPATH can be set for executables or libraries that dynamically link to other libraries. If you have such cases, you may need it.

> Meanwhile, what were the things you did with `RPATH`?
> 
> ```cmake
>   if(APPLE)
>     set_target_properties(layout PROPERTIES BUILD_WITH_INSTALL_RPATH TRUE INSTALL_RPATH "@loader_path")
>   else()
>     set_target_properties(layout PROPERTIES BUILD_RPATH_USE_ORIGIN TRUE)
>   endif()
> ```

I don't have a reference for this, this is based mostly on my (possibly incomplete) understanding of the RPATH handling in CMake. Some info can be found on CMake wiki [1].

The idea is the following: Because you are moving libraries to their final destinations in setup.py using setuptools, the CMake has no idea about the final destinations for the libraries, so setting a specific absolute RPATH is not an option. The only choice left would be to use a relative RPATH, which would make libraries "relocatable". But one thing about RPATH is that you don't just set them to something like "./../foo/lib", but instead have to specify it using $ORIGIN like "$ORIGIN/../foo/lib". Presumably, all that's needed for this to work in CMake is to set `BUILD_RPATH_USE_ORIGIN` to `TRUE`. And this would work on Linux and some BSD's, but on macOS things are a bit more sophisticated, it has multiple different keywords that it understands: `@loader_path`, `@executable_path` and `@rpath`, so this, I guess, doesn't fit into the standard $ORIGIN definition, so I manually set `INSTALL_RPATH` to `"@loader_path"`. Finally, CMake has this quite unique feature where RPATH is not just set with linker flags, but can also be updated with new RPATH (e.g. see [2]) when the binaries are installed (copied from the build directory to their prefixes in the `CMAKE_INSTALL_PATH`). Since we are aiming for relocatable binaries, I just let it make linker do it since the beginning by setting `BUILD_WITH_INSTALL_RPATH` to `TRUE`.

[1] https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling
[2] https://github.com/NixOS/patchelf : AFAIK patchelf is not used by CMake, but, I believe, it well illustrates what is being done

File: CMakeLists.txt [hunk 1]
```diff
@@ -1,6 +1,7 @@
 # BSD 3-Clause License; see https://github.com/jpivarski/awkward-1.0/blob/master/LICENSE
 
 cmake_minimum_required(VERSION 3.10...3.16)
+option(USE_CLANG "build application with clang" ON)
```
Comment (veprbl) [inline CMakeLists.txt]: Perhaps, this should not get in.

File: CMakeLists.txt [hunk 2]
```diff
@@ -13,6 +14,7 @@ if(CMAKE_BUILD_TYPE IN_LIST SIMPLE_TYPES)
 else()
   message(STATUS "CMAKE_BUILD_TYPE = ${CMAKE_BUILD_TYPE}")
 endif()
+message(STATUS "Compiler ${CMAKE_CXX_COMPILER_ID}")
```
Comment (veprbl) [inline CMakeLists.txt]: CMake already reports the compiler for you.

File: include/awkward/Identities.h [hunk 3]
```diff
@@ -262,7 +262,7 @@ namespace awkward {
   ///    - {@link IdentitiesOf Identities32}, which is `IdentitiesOf<int32_t>`
   ///    - {@link IdentitiesOf Identities64}, which is `IdentitiesOf<int64_t>`
   template <typename T>
-  class EXPORT_SYMBOL IdentitiesOf: public Identities {
+  class EXPORT_SYMBOL EXPORT_TYPE IdentitiesOf: public Identities {
```
Comment (veprbl) [inline include/awkward/Identities.h]: I suppose, `EXPORT_SYMBOL` is a requirement strictly stronger than `EXPORT_TYPE`, so this won't be very useful.

File: src/python/_io.cpp [hunk 4]
```diff
@@ -93,17 +92,3 @@ make_fromroot_nestedvector(py::module& m, const std::string& name) {
      py::arg("initial") = 1024,
      py::arg("resize") = 1.5);
 }
```
Comment (veprbl) [inline src/python/_io.cpp:94]: Logically, the methods could go to _ext.cpp, especially given that you add the src/awkward1/_io.py placeholder. Another option I see is to remove underscores to have io.cpp.

File: CMakeLists.txt (hunk 1 above)
Comment (jpivarski) [reply CMakeLists.txt]: Yikes! Thanks for catching that. Yes, it when I was trying to do some clang builds on Linux. CMake was ignoring this option, though.

File: CMakeLists.txt (hunk 2 above)
Comment (jpivarski) [reply CMakeLists.txt]: I didn't see it before, but now I do. I'll remove this as well.

File: include/awkward/Identities.h (hunk 3 above)
Comment (jpivarski) [reply include/awkward/Identities.h]: I wasn't able to find any information about the relationship between `__attribute__((visibility("default")))` and `__attribute__((type_visibility("default")))`. Or for that matter `type_visibility` vs `__type_visibility__`. I could determine experimentally that only Clang knew about `type_visibility`; GCC didn't recognize it. From there, I just tried every combination, as you could see.

I thought it might be relevant because all of the symbol visibility linker errors concern `typeinfo` symbols. Everything is hidden by default (pybind11 requires this), so I'm labeling just the things that _should_ be externally visible with a macro. I want this to include the `typeinfo` of concrete classes, but apparently the normal `visibility` doesn't do that. I had hoped `type_visibility` would fill in where `visibility` failed.

I've reverted all the `EXTERNAL_TYPE` declarations.

File: src/python/_io.cpp (hunk 4 above)
Comment (jpivarski) [reply src/python/_io.cpp:94]: Since it's coming from _ext now, I suppose there's no reason to move objects from one hidden module to another. (Users should not be directly calling functions like `fromroot_nestedvector`.)

Since "_io" is no longer a Python module name, I suppose there's no point in keeping the underscore. Renamed.

**Comment by jpivarski** [comment]
> RPATH can be set for executables or libraries that dynamically link to other libraries. If you have such cases, you may need it.

Thanks for the explanation! This sounds important for all of the libraries that would need to be linked against, including libawkward-cpu-kernels and libawkward, so I've applied this technique to each. The number of properties applied to every library is growing, so I may need to wrap them up in a CMake function someday.

Also, thanks for the thorough review. I appreciate it!

**Comment by jpivarski** [comment]
Note: all of the MacOS warnings are about `typeinfo` in these three classes:

```
typeinfo for awkward::IndexedArrayOf<long long, true>
typeinfo for awkward::ListOffsetArrayOf<long long>
typeinfo name for awkward::ListOffsetArrayOf<long long>
```

**Comment by jpivarski** [comment]
The One Weird Trick was based on https://stackoverflow.com/questions/307352/g-undefined-reference-to-typeinfo and eternally springing hope.

Maybe it's relevant that it's only three classes that have `typeinfo` link errors, and the warnings are new.

**Comment by jpivarski** [comment]
Bisecting through Azure's history, the MacOS `typeinfo` warnings were first seen in 79cc9a75b464b54ad04cbde505c967cc74699b74, which is a very useful hint. This is when methods that return one specific `Content` subclass (`toListOffsetArray64` and `toIndexedOptionArray64`) were given this as a return type, rather than the more generic `ContentPtr`. Apparently, that's a problem for Cling or MacOS. I will revert that change, since it wasn't really needed and the `dynamic_casts` that it would have made unnecessary haven't been removed yet, anyway.

**Comment by jpivarski** [comment]
This is probably going to do it. Even though the virtual destructors were irrelevant for these `typeinfo` warnings, I'm going to leave them in the headers because they're trivial (no code) and the immediate information they give (the fact that they're trivial) is useful at the class-definition level, so they can be an exception to the rule that all implementations go in .cc files.

In case I don't mention it before closing it, this PR dealt with two issues that at first seemed related, but in the end were not:

   * `typeinfo` mismatch in different Python extension modules, solved by ce9c2fb2bea2489eb05048c2630070d52c70b09c, whcih combines Python extension modules into a single module. This problem could be relevant again for dependent projects that produce Awkward Arrays; if so, follow that up in issue #211.
   * Linker warnings about the visibility of `typeinfo` symbols. This issue was first raised by @ianna in an email, and I've been wanting to fix it because I don't know if there could be downstream implications. (That's why I immediately thought there might be a connection between these two issues.)

Both of these affected only MacOS (or just Clang?) and the first issue was intermittent (not failing in Azure until #210).

The first CI run with e2ddce3066ea05f935006a5d44ce31c2feb3af12 is complete; it fixed some but not all of the warnings. Definitely the right track.

**Comment by jpivarski** [comment]
Now the remaining warnings are:

```
Compiling libawkward:

awkward::IndexedArrayOf<int, false>::mergeable(std::__1::shared_ptr<awkward::Content> const&, bool) const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<int, false>::merge(std::__1::shared_ptr<awkward::Content> const&) const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<int, false>::simplify_optiontype() const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<int, true>::mergeable(std::__1::shared_ptr<awkward::Content> const&, bool) const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<int, true>::merge(std::__1::shared_ptr<awkward::Content> const&) const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<int, true>::simplify_optiontype() const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<long long, false>::mergeable(std::__1::shared_ptr<awkward::Content> const&, bool) const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<long long, false>::merge(std::__1::shared_ptr<awkward::Content> const&) const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<long long, false>::simplify_optiontype() const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<long long, true>::mergeable(std::__1::shared_ptr<awkward::Content> const&, bool) const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<long long, true>::merge(std::__1::shared_ptr<awkward::Content> const&) const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<long long, true>::simplify_optiontype() const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<unsigned int, false>::mergeable(std::__1::shared_ptr<awkward::Content> const&, bool) const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<unsigned int, false>::merge(std::__1::shared_ptr<awkward::Content> const&) const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<unsigned int, false>::simplify_optiontype() const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>

Compiling the Python module:

awkward::IndexedArrayOf<int, false>::mergeable(std::__1::shared_ptr<awkward::Content> const&, bool) const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<int, false>::merge(std::__1::shared_ptr<awkward::Content> const&) const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<int, false>::simplify_optiontype() const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<int, true>::mergeable(std::__1::shared_ptr<awkward::Content> const&, bool) const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<int, true>::merge(std::__1::shared_ptr<awkward::Content> const&) const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<int, true>::simplify_optiontype() const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<long long, false>::mergeable(std::__1::shared_ptr<awkward::Content> const&, bool) const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<long long, false>::merge(std::__1::shared_ptr<awkward::Content> const&) const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<long long, false>::simplify_optiontype() const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<long long, true>::mergeable(std::__1::shared_ptr<awkward::Content> const&, bool) const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<long long, true>::merge(std::__1::shared_ptr<awkward::Content> const&) const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<long long, true>::simplify_optiontype() const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<unsigned int, false>::mergeable(std::__1::shared_ptr<awkward::Content> const&, bool) const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<unsigned int, false>::merge(std::__1::shared_ptr<awkward::Content> const&) const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
awkward::IndexedArrayOf<unsigned int, false>::simplify_optiontype() const
    wants typeinfo for awkward::IndexedArrayOf<long long, true>
```

**Comment by jpivarski** [comment]
Or more simply:

```
Compiling libawkward:

IndexedArray::mergeable(shared_ptr<Content> const&, bool) const
    wants typeinfo for IndexedArray
IndexedArray::merge(shared_ptr<Content> const&) const
    wants typeinfo for IndexedArray
IndexedArray::simplify_optiontype() const
    wants typeinfo for IndexedArray

Compiling the Python module:

IndexedArray::mergeable(shared_ptr<Content> const&, bool) const
    wants typeinfo for IndexedArray
IndexedArray::merge(shared_ptr<Content> const&) const
    wants typeinfo for IndexedArray
IndexedArray::simplify_optiontype() const
    wants typeinfo for IndexedArray
```

**Comment by jpivarski** [comment]
I'm not going to be able to solve these last few warnings; maybe I'll get back to them someday.

Once these tests pass, I'm merging the PR.
