### ISSUE TITLE
`ak.to_cudf` fails with `TypeError` on cuDF 24.12 due to internal API changes

### ISSUE THREAD

**Issue by ianna** [scikit-hep/awkward#3783]
### Version of Awkward Array

2.8.11

### Description:

Calling `ak.to_cudf` on jagged or nested arrays fails when using `cudf>=24.12.00`. The internal cuDF column constructors (`NumericalColumn` and `StructColumn`) have changed their signatures, leading to `TypeError` when awkward attempts to pass the data keyword argument.

### Reproducer:

```python
import awkward as ak
import cudf

# 1. Jagged array failure (NumericalColumn)
arr_jagged = ak.Array([[[1, 2, 3], [], [3, 4]], []])
out_jagged = ak.to_cudf(arr_jagged)

# 2. Nested record failure (StructColumn)
arr_nested = ak.Array([{"a": {"b": 1}}, {"a": {"b": 2}}])
out_nested = ak.to_cudf(arr_nested)
```

#### For Jagged Arrays:

```
E TypeError: NumericalColumn.__init__() got an unexpected keyword argument 'data'
...
/awkward/contents/listoffsetarray.py:2015: in _to_cudf
> ind_buf = cudf.core.column.numerical.NumericalColumn(
    data=buf, dtype=index.dtype, mask=None, size=len(index)
  )
```

#### For Nested Records:

```
E TypeError: StructColumn.__init__() got an unexpected keyword argument 'data'
...
/awkward/contents/recordarray.py:1150: in _to_cudf
> return cudf.core.column.struct.StructColumn(
    data=None,
    children=children,
    dtype=dt,
    mask=m,
    size=length,
    offset=0,
)
```

**Comment by ikrommyd** [comment]
There's potentially other column constructors too that are used in awkward code and are just not tested in the gpu tests that have changed. Every `def _to_cudf` implementation for all layouts potentially needs patching.

**Comment by aashirvad08** [comment]
Hi!   
I recently had a PR merged into Awkward Array.

I’d like to reproduce this `ak.to_cudf` failure with cuDF 24.12 and work on a fix if no one else is currently working on it.
Please let me know if that’s okay.

**Comment by ianna** [comment]
@X0708a - Thank you very much for your contribution! Yes, please take this issue. Very much appreciated! Thanks!

**Comment by ianna** [comment]
@X0708a - to reproduce the failure please revert the changes introduced in https://github.com/scikit-hep/awkward/pull/3781. Thanks!

**Comment by aashirvad08** [comment]
I’m on macOS, so I can’t import cudf locally.
I reverted #3781 and inspected the affected _to_cudf paths directly.
I’ll prepare a fix and rely on CI for GPU validation.
